<?php

use Illuminate\Database\Seeder;

class CharactersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $game_id = 1;
        $names = [
            "Accursed",
            "Aluna",
            "Amun-Ra",
            "Andromeda",
            "Arachna",
            "Armadon",
            "Artesia",
            "Artillery",
            "Balphagore",
            "Behemoth",
            "Berzerker",
            "Blacksmith",
            "Blitz",
            "Blood Hunter",
            "Bombardier",
            "Bramble",
            "Bubbles",
            "Bushwack",
            "Calamity",
            "Chronos",
            "Circe",
            "Corrupted Disciple",
            "Cthulhuphant",
            "Dampeer",
            "Deadlift",
            "Deadwood",
            "Defiler",
            "Demented Shaman",
            "Devourer",
            "Doctor Repulsor",
            "Draconis",
            "Drunken Master",
            "Electrician",
            "Ellonia",
            "Emerald Warden",
            "Empath",
            "Engineer",
            "Fayde",
            "Flint Beastwood",
            "Flux",
            "Forsaken Archer",
            "Gauntlet",
            "Gemini",
            "Geomancer",
            "Glacius",
            "Gravekeeper",
            "Grinex",
            "Gunblade",
            "Hammerstorm",
            "Hellbringer",
            "Jeraziah",
            "Kane",
            "Keeper of the Forest",
            "Kinesis",
            "King Klout",
            "Klanx",
            "Kraken",
            "Legionnaire",
            "Lodestone",
            "Lord Salforis",
            "Magebane",
            "Magmus",
            "Maliken",
            "Martyr",
            "Master Of Arms",
            "Midas",
            "Moira",
            "Monarch",
            "Monkey King",
            "Moon Queen",
            "Moraxus",
            "Myrmidon",
            "Night Hound",
            "Nitro",
            "Nomad",
            "Nymphora",
            "Oogie",
            "Ophelia",
            "Pandamonium",
            "Parallax",
            "Parasite",
            "Pearl",
            "Pebbles",
            "Pestilence",
            "Pharaoh",
            "Plague Rider",
            "Pollywog Priest",
            "Predator",
            "Prisoner 945",
            "Prophet",
            "Puppet Master",
            "Pyromancer",
            "Rally",
            "Rampage",
            "Ravenor",
            "Revenant",
            "Rhapsody",
            "Riftwalker",
            "Riptide",
            "Salomon",
            "Sand Wraith",
            "Scout",
            "Shadowblade",
            "Shellshock",
            "Silhouette",
            "Sir Benzington",
            "Skrap",
            "Slither",
            "Solstice",
            "Soul Reaper",
            "Soulstealer",
            "Succubus",
            "Swiftblade",
            "Tarot",
            "Tempest",
            "The Chipper",
            "The Dark Lady",
            "The Gladiator",
            "The Madman",
            "Thunderbringer",
            "Torturer",
            "Tremble",
            "Tundra",
            "Valkyrie",
            "Vindicator",
            "Voodoo Jester",
            "War Beast",
            "Wildsoul",
            "Witch Slayer",
            "Wretched Hag",
            "Zephyr",
        ];

        foreach ($names as $name)
        {
            App\Character::create([
                'name' => $name,
                'game_id' => $game_id
            ]);
        }
    }
}
